"""empty message

Revision ID: 6790cf31bd9e
Revises: d87f42d0911b
Create Date: 2017-01-24 15:27:26.261694

"""

# revision identifiers, used by Alembic.
revision = '6790cf31bd9e'
down_revision = 'd87f42d0911b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'customer_id')
    ### end Alembic commands ###
