"""empty message

Revision ID: d87f42d0911b
Revises: 82184d7d1e88
Create Date: 2017-01-24 11:14:06.870920

"""

# revision identifiers, used by Alembic.
revision = 'd87f42d0911b'
down_revision = '82184d7d1e88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription', sa.DateTime()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription')
    ### end Alembic commands ###
